# site properties and page defaults
title: Macroecology Lab
subtitle: at Tohoku University
description: We use statistical models and geospatial techniques to predict  species’ ranges and their relationships with the environment, make estimates of biodiversity and map its patterns, and predict how biodiversity will change in the future.
header: images/background.jpg
footer: images/background.jpg

# site social media and other links
links:
  email: kass@tohoku.ac.jp
  orcid: 0000-0002-9432-895X
  google-scholar: LM_UNdkAAAAJ
  github: macroecolab-tohoku
  twitter: 
  youtube: 

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
